---
title: "versions"
output: 
  html_document:
    css: document.css

---

\

## 1. BuyTheDips %>% dashboard versions

- The dashboard is constantly improving! I'm not a webdesigner or programmer by any means. Thank you for your patience!

\

### Version 2.2.0 | January 9th, 2022.

I want to thank everyone for using the dashboard! I'm really happy that people are getting uses out of it. I'm getting tons of love and feedback on twitter and I am working towards implementing every single one of them. With that said, I'm just one guy and this is just side hobby for me so updates might take some time. 


##### **Frontend**:
1. Filter limit has been set to 12. It just works a little better when the app isn't trying to update 25 cryptos at once for all the connected users.
2. Added a top filter bar for cryptocurrency categories. This will look better as I add more cryptos to the platform.
3. Took out ALL the stupid google ads. They weren't paying that much, and it was significantly slowing down my website. So good bye Google!

##### **Backend**:
1. After awesome tweets by Adam (@abetrade) and Ryan (@CanteringClark), I realized that I needed to upgrade the servers yet again. I'm running c6g.2xlarge now and pretty satisfied so far. 

##### **Twitter**:
1. I'm getting rid of jpegs altogether now and just keeping the gifs. 

#### **Under development**:
1. I've been playing around with coinbase, binance, and crypto.com apis for orderbooks. I think I can roll out a new metric in the next update that will provide insight into market sentiment based on bids/asks. I think I will also make a new graph that will show buy and sell walls within z-score increments. Think it'll be fun.
2. I think the backend has been scaled enough to handle more cryptocurrencies now, so I will definitely add more in the coming weeks. Let me know on twitter if there are any that you absolutely want included into dashboard. 
3. I've gotten a suggestion on including a metric related to beta (slope). 
4. I've been suggestions to make tutorial videos on YouTube. I don't know if I'll have time for this. I will try to update the documentation in the meantime.  

\

### Version 2.1.0 | December 23th, 2021.

##### **Front-end**:
1. Added filter table to the dashboard.
2. Added graph tooltips/explanations to the dashboard (hover question marks).
3. Added longer duration to historicals (since Oct 30th, 2021 when I started tracking z-scores). 
4. Market cap dominance calculations have been updated to be more realiable. Now it's measured as change against bitcoin market cap.

##### **Back-end**:
1. It's come to my attention that shiny apps are limited to one CPU worker per app. So I've been trying to scale up shiny app using shinyproxy/docker, but there was a weird callback bug with datatable module that specifically messed up the filter table. I think I've found a work-around for now by using nginx as a load balancer to multiple shiny apps. 
2. With that said, a helpful webdeveloper on twitter (@itsmlyup) has told me that it will be hard to scale my shiny app any further without rewriting everything from scratch with javascript! I will try to work on this in the coming weeks, but at the same time, I am realizing that I am way in over my head. 

##### **Twitter**:
1. I am changing the tweet frequency from every hour to every two hours. As the dashboard website gets more stable/usable, I will continue to change the twitter frequency. 
2. It seems like people are using the limit feature on the dashboard which makes Mole somewhat obsolete, so I am considering taken **Mole** offline. It's a little sad cause I think Mole is hilarious.

\

### Version 2.0.0 | December 16th, 2021.

- Renovated user-interface.
- Added a **voting page for twitter updates** (left panel menu > “VOTE”). Because I wanted to keep voting completely anonymous and you can actually vote multiple times over different sessions. Voting closes on the first of every month (2pm EST). 
- Added **correlation matrix** for price movements and trading volumes. Found in “Historical” tabs.
- Moved volatility graphs to their own tab.

\

### Version 1.3.1 | December 10th, 2021.

- A generous anonymous donor left me 5 ADAs this week! This is the single largest donation I've ever had and I am so grateful to your contribution! Thank you very much!
- I made some major upgrades on the backend that should improve user experience: 
1) Most calculations will occur off the shiny web app now, and it should speed up the website in the next 48 hours.
2) Upgraded AWS server to a compute-optimized instance (C6g). I tried T2, T4 and A1 EC2 instances so far and they were just really unreliable no matter how many CPU credits I was accumulating off peak hours. 
3) Implemented a proper web-app time-out procedure. The dashboard web app was not exiting properly after people disconnected from their phones, leaving the server connected to them indefinitely. So hopefully this fixes that. Timeout is 4269 seconds (~71 minutes) of inactivity, so most of you guys won't see this.
- We've held our first votes for twitter account page. I will hold these votes every 2-weeks so we have a consistent turnover of cryptos. I might code in a voting app on the dashboard so that people can vote anonymously. I will try to include coins that were mentioned but did not win into the dashboard.
- Some of you guys may have noticed that I started running ads. I hate it so much, especially the google's auto-ad placement. But I want this dashboard to become financially self-sustaining. No pressure but please feel free to click on them once in a while lol.

\

### Version 1.3.0 | December 3rd, 2021.

- Happy Friday! We've had tons of traffic this week to the dashboard. It was a crazy week for the servers. Sorry if you've experiences outages.
- Fixed the mobile navigation button blackhole.
- Added Mole's limits to the dashboard. 
- Enter your budget and Mole will suggest limit buy and sell points based on current z scores. They're essentially **!getspicy** of the twitter version, but the twitter version only updates every 20 minutes while the dashboard one updates every 5 minutes.
- People seem to really enjoy the animations on the main twitter bot. I'm trying to think of ways I can incorporate this into the website. 

\

### Version 1.2.2 | November 25th, 2021.

- Good news: Days since chart is should now be stable and reliable! 
- Most changes were made on the backend this week that increases performance and decreases loading time. In other words, I cleaned up my code lol.
- I added a 'full screen' option to the historical charts. 
- I've been working on the portfolio manager that uses BuyTheDip metrics. I'm pretty happy with how things are going, and I'm hoping that it'll help crypto investors and traders make better decisions. Let me know on Twitter if you'd like to be a beta tester for this feature when its ready. 

\

### Version 1.2.0 | November 16th, 2021.

- Thank you all for your interest in the **BuyTheDips** dashboard! 
- I'm sorry that the server has been unstable. The cold-hard-truth is that I made the app on Amazon AWS free-trial server which has limited capabilities. I'm bashing on my keyboard as fast as I can.
- The initial release a week ago helped better understand server requirements moving forward. Unlike your traditional blog pages, the **BuyTheDips dashboard** app is actually quite CPU heavy with each user. So the server crashes/slows-down everytime there's an uptick of traffic.  
- To unload some server CPU usage, the historical charts were moved off the main app and they are uploaded every hour as *html widgets*. You can still filter them and scroll them, but you can't change their color anymore. 
- Few additional indicators and metrics were added (explained below).
- Features have become slightly more mobile friendly.
- I think I will be able to add even more cryptos in the future updates, but I think I will prioritize stabilitizing the server first.

\

### Version 1.0.0 | November 10th, 2021.

- Launched BuyTheDips dashboard.
- Dashboard updates automatically every 5 minutes. 
- 'Reset axis' button on plotly graphs resets the timeframe (x-axis) to 3 days, and 'Auto-scaling' button resets plot to 12 days. 
- While you can filter cryptocurrencies by either clicking on the panel at the top, or on the legends, only the top filter changes are sustainable through updates. 

\

## 2. Future development/work-in-progress

\

### 2.1 Portfolio manager on BuyTheDips website is under development. 
- I'm hoping to make the best product that crypto investors have been looking for. It's coming soon, I promise. I'm coding as fast as I can. 

### 2.2 Machine learning based short-term predictions for z-scores 
- Mole has been learning cryptocurrency metrics and indicators. At some point, Mole will start sharing her predictions with us. Stay tuned!

\

## 3. Reach out for suggestions

\

- You can find me on reddit (u/Ahjustsea) or on twitter (@bitcoinDips).
- If you would like to support BuyTheDips, you can make a donation below. Any support will be greatly appreciated. Thank you!

\

**BTC**: bc1qcay52dwm8h7qugj4tkzjcg0wrzhqf9jsh62sgn 

**ETH**: 0xA1e608C40C88B83e3325a9f25E0523BE8bC977d2 

**ADA**: Ae2tdPwUPEZMc9Jp6RVE4SfCKpQCQD4LMZKiSaoyCtSzTE5JNrZNrvBiyTT 

**SOL**: 8oETiSiMJhR1iMSPqWQDZ24qhToxfdBZHG5AP9Jfimv6 

**XLM**: GBC7BWLJ7LPGZGNSBOQQAGA4IQB3OINZ3WT7FHUQ3XRAWFJQC56X34XL 

**USDT**: 0xA1e608C40C88B83e3325a9f25E0523BE8bC977d2

**DOGE**: DKwBg5xx946AMYrSQL1ZecGazetWHRe7Rs 

**SHIB**: 0xA1e608C40C88B83e3325a9f25E0523BE8bC977d2 

**r/cc MOON**: 0x1a5fce959e9e6574cba3893f9d3abcc127d8c82b 
